"allProducts": [{
  "name" : "Emerson Bar Chair",
  "productID" : "f12648",
  "price" : 120.00,
  "description" : "This Emerson Bar Chair is made from sturdy wood, hand carved and has curves and rounded shaped legs along with nail head trim with a polished footrest for comfort.",
  "specifications" : ["18in L x 18in W x 25in H · Chair extends to 30inch H","Wood, Steel"],
  "reviews" : [],
  "imageURL" : "https://cdn.shopify.com/s/files/1/1386/1639/products/12648_grande.jpg?v=1471977535",
  "storyCategory" : "Industrial",
  "roomCategory" : ["Kitchen&Dining", "Living"],
  "productCategory" : ["Furniture"]
}, {
  "name" : "Watering Hole Stool",
  "productID" : "f12638",
  "price" : 145.00,
  "description" : "Industrial vintage bar stool with polished steel base with a wooden seat and back.",
  "specifications" : ["18in W x 38in H", "Seat adjusts from 25H to 30H", "Silver, Woodgrain"],
  "reviews" : ["Love the look of this bar stool!", "Looks great at my breakfast bar. Purchasing two more!"],
  "imageURL" : "https://cdn.shopify.com/s/files/1/0189/1672/products/12638_530x.jpg?v=1482002903",
  "storyCategory" : "Industrial",
  "roomCategory" : ["Kitchen&Dining"],
  "productCategory" : ["Furniture"]
}, {
  "name" : "Industrial Storage Coffee Table",
  "productID" : "f12640",
  "price" : 345.00,
  "description" : "Lofted on airy steel legs, our Industrial Storage Coffee Table's top pops up to reveal a boatload of hidden storage.",
  "specifications" : ["Overall product dimensions: 36in W x 26in D x 17.75in H (25in H when open)", "Interior compartment: 32in W x 22in D x 6.5in H", "Cafe, Black Powdercoated Metal"],
  "reviews" : ["Perfect for my small studio."],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201711/0141/industrial-storage-coffee-table-c.jpg",
  "storyCategory" : "Industrial",
  "roomCategory" : ["LivingRoom"],
  "productCategory" : ["Furniture"]
}, {
  "name" : "Metalwork 6-Drawer Dresser - Hot-Rolled Steel Finish",
  "productID" : "f12610",
  "price" : 630.00,
  "description" : "Finished in hot-rolled steel for a cool, industrial edge, our Metalwork Dresser is one of our all-time favorites—and with its clean lines and simple proportions, it's easy to see why.",
  "specifications" : ["55.1in w x 18in d x 32.4in h.", "Metal in a Hot-Rolled Steel finish."],
  "reviews" : ["Heavy as hell but looks great in my bedroom. Looking forward to seeing it patina a bit.", "If I had room, I would get the matching side dressers."],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201709/0002/metalwork-6-drawer-dresser-hot-rolled-steel-finish-c.jpg",
  "storyCategory" : "Industrial",
  "roomCategory" : ["Bedroom"],
  "productCategory" : ["Furniture"]
}, {
  "name" : "Massaro Metal-Wrapped 6-Drawer Dresser - Hot-Rolled Steel",
  "productID" : "f01638",
  "price" : 645.00,
  "description" : "With its low profile, clean lines and industrial-inspired metal case, our handsome Massaro Dresser feels rustic and refined all at once. We finished off its minimalist form in a cool gray-brown Umber finish—one of our favorites for the season.",
  "specifications" : ["56in w x 18in d x 26.1in h.", "Oak veneer over solid wood drawers in an Umber finish.", "Metal case and hardware in a Hot-Rolled Steel finish."],
  "reviews" : ["Amazing!!", "Thought this dresser would look too industrial, but the wood drawers paired with steel really make it!"],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201709/0007/massaro-metal-wrapped-6-drawer-dresser-c.jpg",
  "storyCategory" : "Industrial",
  "roomCategory" : ["Bedroom"],
  "productCategory" : ["Furniture"]
}, {
  "name" : "Logan Platform Bed - Smoked Brown",
  "productID" : "f00638",
  "price" : 845.00,
  "description" : "Made of solid wood, re-sawing and rough-hewing give our Logan Collection its rugged good looks. The process makes each piece subtly one-of-a-kind.",
  "specifications" : ["Queen: 73in w x 87.5in d x 48.2in h.", "Solid acacia wood in a Smoked Brown finish"],
  "reviews" : ["Sturdy!", "Simple design. Looks great in my loft but I need to figure out how to keep the mattress from slipping on the platform."],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201646/0005/logan-platform-bed-smoked-brown-1-c.jpg",
  "storyCategory" : "Industrial",
  "roomCategory" : ["Bedroom"],
  "productCategory" : ["Furniture"]
}, {
  "name" : "Faceted Stone Table Lamp",
  "productID" : "l12345",
  "price" : 115.00,
  "description" : "The geometric sides of our Faceted Stone Table Lamp are carved into black soapstone. Topped with a crisp white shade, its polished look works well in rooms modern and traditional alike.",
  "specifications" : ["13in diam. x 23in h.", "Accommodates a 13W CFL bulb (included) or 60W incandescent bulb (not included).", "Rotary On/Off switch."],
  "reviews" : ["Love this table lamp!", "Wish this came as a white base, but the black stone is still stunning. Happy with my purchase."],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201711/0091/faceted-stone-table-lamp-c.jpg",
  "storyCategory" : "Industrial",
  "roomCategory" : ["LivingRoom", "Bedroom"],
  "productCategory" : ["Lighting"]
}, {
  "name" : "Industrial Task Table Lamp + USB",
  "productID" : "l02112",
  "price" : 43.00,
  "description" : "Our Industrial Task Table Lamps fuse form and function, swiveling and adjusting to direct light wherever it’s needed. A USB port at its base makes it a great spot to charge your phone.",
  "specifications" : ["7in diam. x 33in h.", "Adjustable arm locks at two angles.", "Does the job.  What can I say?"],
  "reviews" : ["Great task lamp and look.", "Looks great at my breakfast bar. Purchasing two more!"],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201652/0021/industrial-task-table-lamp-usb-1-c.jpg",
  "storyCategory" : "Industrial",
  "roomCategory" : ["LivingRoom", "Bedroom"],
  "productCategory" : ["Lighting"]
}, {
  "name" : "Bontok Theatre Floor Lamp",
  "productID" : "l12222",
  "price" : 45.00,
  "description" : "Oversized metal shape is inspired by old lamps from places like factories and theaters.",
  "specifications" : ["71in H x 12in diam.", "Iron black coating."],
  "reviews" : ["Yay, light in my living room!", "Not what I expected.  Nice lamp, but will be returning."],
  "imageURL" : "http://www.ikea.com/us/en/images/products/hektar-floor-lamp-gray__0149974_PE308131_S4.JPG",
  "storyCategory" : "Industrial",
  "roomCategory" : ["LivingRoom"],
  "productCategory" : ["Lighting"]
}, {
  "name" : "Sol Duvet Cover",
  "productID" : "t11110",
  "price" : 45.00,
  "description" : "Ultra soft duvet cover made from 100% Certified Organic Cotton.",
  "specifications" : ["Queen: 80in x 89in.", "300 Thread Count.", "Sateen Weave, Single Ply."],
  "reviews" : ["warm and cozy", "Lovely Blue Duvet Cover", "expectations were met","So soft and comfortable. Love that it's organic cotton. Wish there were ties to keep the duvet in place."],
  "imageURL" : "https://cdn.shopify.com/s/files/1/1094/4634/products/Duvet-Cover-Blue_aad01783-9e87-407f-bca9-a365699da9ee_2048x2048.jpg?v=1483720142",
  "storyCategory" : "nil",
  "roomCategory" : ["Bedroom"],
  "productCategory" : ["Textiles"]
}, {
  "name" : "Hemmed Sheet Set",
  "productID" : "t12118",
  "price" : 45.00,
  "description" : "These cool, soft & breathable sateen sheets will create that home away from home experience.",
  "specifications" : ["Ultra Soft Fine Long Staple", "100% Certified Organic Cotton", "300 Thread Count"],
  "reviews" : ["We are very happy with the feel of these sheets. They are soft and light weight. Will definitly order another set.", "Overall, we are pleased, and ordered a 2nd set + additional pillow cases. We aren't blown away by their immediate hand; even after a delicate cold wash and no-heat dry, the sheets don't feel that soft to the touch. Gliding your hand over them, they almost have an abbrasiveness. Surprisingly, we still find them very comfortable to sleep in. They drape lightly and breath well. The ethical production of them is more important to us then having the softest feeling sheets ever"],
  "imageURL" : "https://cdn.shopify.com/s/files/1/1094/4634/products/Folded-sheets-white_7d97d006-352c-4adb-a438-b544cc915dfc_2048x2048.jpg?v=1488223990",
  "storyCategory" : "nil",
  "roomCategory" : ["Bedroom"],
  "productCategory" : ["Textiles"]
}, {
  "name" : "Quilted Madison Sham",
  "productID" : "t77638",
  "price" : 15.00,
  "description" : "Made from an extra-fine weave microfiber, the modern quilted design offers texture and style to your décor. The sham is wrinkle-resistant and easy to wash, allowing your bed to look picture perfect every day.",
  "specifications" : ["Standard Size", "100% extra-fine weave microfiber", "Hypo-allergenic"],
  "reviews" : ["This sham is a sham!", "Found these to be as nice as described - beautiful, very soft and high quality, accurate color depiction. Luxurious feel."],
  "imageURL" : "https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&itemId=100026869-847&recipeName=344",
  "storyCategory" : "nil",
  "roomCategory" : ["Bedroom"],
  "productCategory" : ["Textiles"]
}, {
  "name" : "Mediteranean Bath Towels - Set of 4",
  "productID" : "t12228",
  "price" : 125.00,
  "description" : "Turkish bath towels from Coyuchi are super-absorbent, woven for maximum moisture-wicking potential. With proper care, these premium, pampering picks will last you for years.",
  "specifications" : ["Traditional lightweight Turkish bath towels with a high/low weave for excellent absorption.", "Cotton is 100% organic, and sourced and woven in Turkey."],
  "reviews" : ["It took me a while to get used to the idea that a thinner towel could be as absorbent as a thick or plush towel but once I got my head around that, I was hooked. I was given a beach towel from a friend and although I would not normally travel with my own towel, I'm absolutely sure I would make room in my bag for this one. It's practical & beautiful for any sunny holiday!", "Clean beautiful design."],
  "imageURL" : "http://bpc.h-cdn.co/assets/16/01/768x384/landscape-1452115931-turkish-bath-towels.jpg",
  "storyCategory" : "nil",
  "roomCategory" : ["Bathroom"],
  "productCategory" : ["Textiles"]
}, {
  "name" : "Warmest Throw – Yarn Dyed",
  "productID" : "t13333",
  "price" : 25.00,
  "description" : "Woven with fun, fringed edges, our Warmest Throw is a cozy classic.",
  "specifications" : ["44in l x 56in w.", "100% acrylic.", "Fringed ends."],
  "reviews" : ["Super soft!!", "Got as a gift and I love it!"],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201651/0010/warmest-throw-yarn-dyed-o.jpg",
  "storyCategory" : "nil",
  "roomCategory" : ["LivingRoom", "Bedroom"],
  "productCategory" : ["Textiles"]
}, {
  "name" : "Symmetry Objects",
  "productID" : "a00123",
  "price" : 15.00,
  "description" : "More than meets the eye. These optical sculptures feature geometric twists and turns, for a multidimensional display.",
  "specifications" : ["Small: 6.75in sq. 6.5in h.", "Iron in Antique Brass."],
  "reviews" : [],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201711/0030/symmetry-objects-c.jpg",
  "storyCategory" : "Industrial",
  "roomCategory" : ["Bedroom", "LivingRoom"],
  "productCategory" : ["Accents"]
}, {
  "name" : "Boos Edge-Grain Rectangular Cutting Board, Walnut",
  "productID" : "c71223",
  "price" : 45.00,
  "description" : "An exceptionally hard cutting board provides a stable work surface and also helps protect finely honed blades. Sturdy construction – with the edge grain creating the work surface – gives this board a commercial-quality toughness to withstand years of use.",
  "specifications" : ["20in x 15in x 1 1/2in thick; 10 lb.", "Crafted in the USA from sustainably harvested North American walnut.", "Edge-grain construction holds up to years of slicing and chopping."],
  "reviews" : ["Purchased it as a gift and he loved it!", "Beautiful cutting board. I almost don't want to use it."],
  "imageURL" : "http://ab.wsimgs.com/wsimgs/ab/images/dp/wcm/201704/0035/img91c.jpg",
  "storyCategory" : "nil",
  "roomCategory" : ["Kitchen&DiningRoom"],
  "productCategory" : ["Cookware"]
}, {
  "name" : "Enclume Sig Steel & Tigerwood Chef's Rack",
  "productID" : "f12255",
  "price" : 125.00,
  "description" : "The beautiful striped markings of Brazilian tigerwood add warmth to this wall-mount hammered-steel rack.",
  "specifications" : ["17in x 36in x 13in high.", "Includes 6 straight and 12 angled hooks.", "Includes moungting hardware."],
  "reviews" : [],
  "imageURL" : "http://ab.wsimgs.com/wsimgs/ab/images/dp/wcm/201702/0006/img35c.jpg",
  "storyCategory" : "nil",
  "roomCategory" : ["Kitchen&DiningRoom"],
  "productCategory" : ["Furniture"]
}, {
  "name" : "KitchenAid® 4 oz. Blade Coffee Grinder",
  "productID" : "sa13344",
  "price" : 25.00,
  "description" : "Features a blade grinding mechanism that rapidly and easily grinds with minimal noise level. It offers easy fingertip control and 1 - 4 cup versatile brew cycle function.",
  "specifications" : ["44in l x 4.25in w x 8.75in h", "Steel construction.", "Bowl, blade and top are dishwasher safe; Wipe exterior clean."],
  "reviews" : ["The KitchenAid Blade Coffee Grinder is very easy to use and clean. It will always grind your coffee to your liking."],
  "imageURL" : "https://s7d1.scene7.com/is/image/BedBathandBeyond/96116818546191p?$478$",
  "storyCategory" : "nil",
  "roomCategory" : ["Kitchen$DiningRoom"],
  "productCategory" : ["SmallAppliances"]
}, {
  "name" : "Peralta Full Dinnerware Set, Chez Panisse Line - Set for 2",
  "productID" : "t13333",
  "price" : 115.00,
  "description" : "The main dinner plate and café bowl in the classic, earthy texture and tone of our new glaze, Sand, is balanced with the saturated color Slate, another new matte glaze highlighted on the salad plate, side bowl and large mug.",
  "specifications" : ["Full Dinnerware Set.", "Set for 2.", "10 piece set."],
  "reviews" : [],
  "imageURL" : "http://rk.weimgs.com/weimgs/rk/images/wcm/products/201651/0010/warmest-throw-yarn-dyed-o.jpg",
  "storyCategory" : "nil",
  "roomCategory" : ["Kitchen$DiningRoom"],
  "productCategory" : ["Dinnerware"]

}]
